all_map = {
    "中国": "China",
    "阿富汗": "Afghanistan",
    "阿联酋": "United Arab Emirates",
    "阿曼": "Oman",
    "阿塞拜疆": "Azerbaijani",
    "巴基斯坦": "Pakistan",
    "巴勒斯坦": "Palestine",
    "巴林": "Bahrain",
    "不丹": "Bhutan",
    "朝鲜": "North Korea",
    "东帝汶": "East Timor",
    "菲律宾": "Philippines",
    "格鲁吉亚": "Georgia",
    "哈萨克斯坦": "Kazakhstan",
    "韩国": "South Korea",
    "吉尔吉斯斯坦": "Kyrgyzstan",
    "柬埔寨": "Cambodia",
    "卡塔尔": "Qatar",
    "科威特": "Kuwait",
    "老挝": "Laos",
    "黎巴嫩": "Lebanon",
    "马尔代夫": "Maldives",
    "马来西亚": "Malaysia",
    "蒙古": "Mongolia",
    "孟加拉国": "Bangladesh",
    "缅甸": "Myanmar",
    "尼泊尔": "Nepal",
    "日本": "Japan",
    "沙特阿拉伯": "Saudi Arabia",
    "斯里兰卡": "Sri Lanka",
    "塔吉克斯坦": "Tajikistan",
    "泰国": "Thailand",
    "土耳其": "Turkey",
    "土库曼斯坦": "Turkmenistan",
    "文莱": "Brunei",
    "亚美尼亚": "Armenia",
    "乌兹别克斯坦": "Uzbekistan",
    "新加坡": "Singapore",
    "叙利亚": "Syria",
    "也门": "Yemen",
    "伊拉克": "Iraq",
    "伊朗": "Iran",
    "以色列": "Israel",
    "印度": "India",
    "印度尼西亚": "Indonesia",
    "约旦": "Jordan",
    "越南": "Vietnam",
    "阿尔及利亚": "Algeria",
    "埃及": "Egypt",
    "埃塞俄比亚": "Ethiopia",
    "安哥拉": "Angola",
    "贝宁": "Benin",
    "博茨瓦纳": "Botswana",
    "布基纳法索": "Burkina Faso",
    "布隆迪": "Burundi",
    "赤道几内亚": "Equatorial Guinea",
    "多哥": "Togo",
    "厄立特里亚": "Eritrea",
    "佛得角": "Cape Verde",
    "冈比亚": "Gambia",
    "刚果（布）": "Congo (Bulgaria)",
    "刚果（金）": "Congo (Kinshasa)",
    "吉布提": "Djibouti",
    "几内亚": "Guinea",
    "几内亚比绍": "Guinea-Bissau",
    "加纳": "Ghana",
    "加蓬": "Gabon",
    "津巴布韦": "Zimbabwe",
    "喀麦隆": "Cameroon",
    "科摩罗": "Comoros",
    "科特迪瓦": "Ivory Coast",
    "肯尼亚": "Kenya",
    "莱索托": "Lesotho",
    "利比里亚": "Liberia",
    "利比亚": "Libya",
    "卢旺达": "Rwanda",
    "马达加斯加": "Madagascar",
    "马拉维": "Malawi",
    "马里": "Mali",
    "毛里求斯": "Mauritius",
    "毛里塔尼亚": "Mauritania",
    "摩洛哥": "Morocco",
    "莫桑比克": "Mozambique",
    "纳米比亚": "Namibia",
    "南非": "South Africa",
    "南苏丹": "southern Sultan",
    "尼日尔": "Niger",
    "尼日利亚": "Nigeria",
    "塞拉利昂": "Sierra Leone",
    "塞内加尔": "Senegal",
    "塞舌尔": "Seychelles",
    "圣多美和普林西比": " Sao Tome and Principe ",
    "斯威士兰": "Swaziland",
    "苏丹": "Sudan",
    "索马里": "Somalia",
    "坦桑尼亚": "Tanzania",
    "突尼斯": "Tunisia",
    "乌干达": "Uganda",
    "赞比亚": "Zambia",
    "乍得": "Chad",
    "中非": "Central Africa",
    "阿尔巴尼亚": "Albania",
    "爱尔兰": "Ireland",
    "爱沙尼亚": "Estonia",
    "安道尔": "Andorra",
    "奥地利": "Austria",
    "白俄罗斯": "Belarus",
    "保加利亚": "Bulgaria",
    "比利时": "Belgium",
    "冰岛": "Iceland",
    "波黑": "Bosnia and Herzegovina",
    "波兰": "Poland",
    "丹麦": "Denmark",
    "德国": "Germany",
    "俄罗斯": "Russia",
    "法国": "France",
    "芬兰": "Finland",
    "荷兰": "Netherlands",
    "黑山": "Montenegro",
    "捷克": "Czech Republic",
    "克罗地亚": "Croatia",
    "拉脱维亚": "Latvia",
    "立陶宛": "Lithuania",
    "列支敦士登": "Liechtenstein",
    "卢森堡": "Luxembourg",
    "罗马尼亚": "Romania",
    "马耳他": "Malta",
    "马其顿": "Macedonia",
    "摩尔多瓦": "Moldova",
    "摩纳哥": "Monaco",
    "挪威": "Norway",
    "葡萄牙": "Portugal",
    "瑞典": "Sweden",
    "瑞士": "Switzerland",
    "塞尔维亚": "Serbia",
    "塞浦路斯": "Cyprus",
    "圣马力诺": "San Marino",
    "斯洛伐克": "Slovakia",
    "斯洛文尼亚": "Slovenia",
    "乌克兰": "Ukraine",
    "西班牙": "Spain",
    "希腊": "Greece",
    "匈牙利": "Hungary",
    "意大利": "Italy",
    "英国": "Britain",
    "安提瓜和巴布达": "Antigua and Barbuda",
    "巴巴多斯": "Barbados",
    "巴哈马": "Bahamas",
    "巴拿马": "Panama",
    "伯利兹": "Belize",
    "多米尼加": "Dominica",
    "多米尼克": "Dominica",
    "哥斯达黎加": "Costa Rica",
    "格林纳达": "Grenada",
    "古巴": "Cuba",
    "海地": "Haiti",
    "洪都拉斯": "Honduras",
    "加拿大": "Canada",
    "美国": "America",
    "墨西哥": "Mexico",
    "尼加拉瓜": "Nicaragua",
    "萨尔瓦多": "El Salvador",
    "圣基茨和尼维斯": "Saint Kitts and Nevis",
    "圣卢西亚": "Saint Lucia",
    "圣文森特和格林纳丁斯": "Saint Vincent and the Grenadines",
    "特立尼达和多巴哥": "Trinidad and Tobago",
    "危地马拉": "Guatemala",
    "牙买加": "Jamaica",
    "阿根廷": "Argentina",
    "巴拉圭": "Paraguay",
    "巴西": "Brazil",
    "秘鲁": "Peru",
    "玻利维亚": "Bolivia",
    "哥伦比亚": "Colombia",
    "厄瓜多尔": "Ecuador",
    "圭亚那": "Guyana",
    "苏里南": "Suriname",
    "委内瑞拉": "Venezuela",
    "乌拉圭": "Uruguay",
    "智利": "Chile",
}
