# Generated by Django 2.1.7 on 2019-04-02 19:13

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('uaccount', models.CharField(max_length=100, unique=True)),
                ('unamech', models.CharField(max_length=100)),
                ('unameen', models.CharField(max_length=100)),
                ('upassword', models.CharField(max_length=100)),
                ('umail', models.CharField(max_length=100, unique=True)),
                ('uphone', login.models.MyCharField(max_length=11)),
                ('uqq', models.CharField(max_length=100, unique=True)),
                ('uall', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
