# Generated by Django 2.1.7 on 2019-04-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aid', models.BigAutoField(primary_key=True, serialize=False)),
                ('afnamech', models.CharField(blank=True, default='nochname', max_length=1000)),
                ('alnamech', models.CharField(blank=True, default='nochname', max_length=1000)),
                ('anamech', models.CharField(blank=True, default='nochname', max_length=1000)),
                ('afnameen', models.CharField(max_length=1000)),
                ('alnameen', models.CharField(max_length=1000)),
                ('anameen', models.CharField(max_length=1000)),
                ('amail', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='AuthorCompany',
            fields=[
                ('acid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acorder', models.SmallIntegerField()),
                ('accurrent', models.BooleanField()),
                ('author', models.ForeignKey(db_column='aid', on_delete=django.db.models.deletion.CASCADE, to='polls.Author')),
            ],
            options={
                'db_table': 'author_company',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cnamech1', models.CharField(max_length=1000)),
                ('cnameeg1', models.CharField(max_length=1000)),
                ('cnamech2', models.CharField(max_length=1000)),
                ('cnameeg2', models.CharField(max_length=1000)),
                ('czipcode', models.CharField(max_length=1000)),
                ('addressch', models.CharField(max_length=1000, null=True)),
                ('addressen', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=1000)),
                ('ptype', models.CharField(max_length=10)),
                ('pifpub', models.BooleanField()),
                ('pplace', models.CharField(max_length=1000)),
                ('ppub', models.CharField(max_length=1000)),
                ('pyear', models.IntegerField()),
                ('ppage', models.BigIntegerField()),
                ('ppath', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('paid', models.BigAutoField(primary_key=True, serialize=False)),
                ('paorder', models.SmallIntegerField()),
                ('pacommunication', models.BooleanField()),
                ('pacorder', models.SmallIntegerField()),
                ('author', models.ForeignKey(db_column='aid', on_delete=django.db.models.deletion.CASCADE, to='polls.Author')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Company')),
                ('paper', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='polls.Paper')),
            ],
            options={
                'db_table': 'paper_author',
            },
        ),
        migrations.AddField(
            model_name='authorcompany',
            name='company',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='polls.Company'),
        ),
    ]
