# Generated by Django 2.1.7 on 2019-04-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='afnamech',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='alnamech',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='anamech',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
